language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install: composer install

script: vendor/bin/phpunit tests

notifications:
  email:
    recipients:
      - ajax@bynder.com
    on_success: never
    on_failure: always