services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\FalBynder\:
    resource: '../Classes/*'

  JWeiland\FalBynder\EventListener\BeforeFileProcessingEventListener:
    tags:
    - name: event.listener
      event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  JWeiland\FalBynder\EventListener\GeneratePublicUrlForResourceEventListener:
    tags:
    - name: event.listener
      event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent

  # Register commands for fal_bynder
  JWeiland\FalBynder\Command\SyncBynderFilesCommand:
    tags:
    - { name: 'console.command', command: 'fal:bynder:sync', schedulable: true }
