services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Bynder2\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Client/BynderClientWrapper'
      - '../Classes/Configuration/BynderAccessTokenConfiguration'
      - '../Classes/Configuration/BynderFalConfiguration'
      - '../Classes/Configuration/BynderPermanentTokenConfiguration'
      - '../Classes/Configuration/GuzzleConfiguration'

  bynder2.cache.fileinfo:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['bynder2_fileinfo']

  bynder2.cache.pagenav:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['bynder2_pagenav']

  bynder2.storages:
    class: SplObjectStorage
    factory: ['@JWeiland\Bynder2\Repository\BynderStorageRepository', 'getBynderStorages']

  JWeiland\Bynder2\Command\SyncBynderFilesCommand:
    arguments:
      $bynderStorages: '@bynder2.storages'
      $fileInfoCache: '@bynder2.cache.fileinfo'
      $pageNavCache: '@bynder2.cache.pagenav'
    tags:
      - {name: 'console.command', command: 'fal:bynder:sync', schedulable: true}

  # Called by makeInstance in BynderDriver
  JWeiland\Bynder2\Configuration\ExtConf:
    public: true

  JWeiland\Bynder2\Controller\AuthorizationUrlController:
    arguments:
      - $bynderStorages: ['@bynder2.storages']

  JWeiland\Bynder2\EventListener\BeforeFileProcessingEventListener:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  JWeiland\Bynder2\EventListener\GeneratePublicUrlForResourceEventListener:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent

  # Called by makeInstance from EXT:backend form elements
  JWeiland\Bynder2\Service\BynderClientFactory:
    public: true

  # Called by makeInstance from EXT:backend form elements
  JWeiland\Bynder2\Service\BynderService:
    public: true

  # Called by makeInstance in BynderDriver
  JWeiland\Bynder2\Utility\OrderingUtility:
    public: true
