services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Bynder2\:
    resource: '../Classes/*'

  # Called by makeInstance in BynderDriver
  JWeiland\Bynder2\Configuration\ExtConf:
    public: true

  # Called by makeInstance in BynderDriver
  # Deactivate autowire as we set constructor arguments on our own
  JWeiland\Bynder2\Service\BynderService:
    autowire: false
    public: true

  JWeiland\Bynder2\Utility\OrderingUtility:
    public: true

  JWeiland\Bynder2\EventListener\BeforeFileProcessingEventListener:
    tags:
    - name: event.listener
      event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  JWeiland\Bynder2\EventListener\GeneratePublicUrlForResourceEventListener:
    tags:
    - name: event.listener
      event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent

  # Register commands for bynder2
  JWeiland\Bynder2\Command\SyncBynderFilesCommand:
    tags:
    - { name: 'console.command', command: 'fal:bynder:sync', schedulable: true }
