services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Bynder2\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Client/BynderClientWrapper'
      - '../Classes/Configuration/BynderAccessTokenConfiguration'
      - '../Classes/Configuration/BynderFalConfiguration'
      - '../Classes/Configuration/BynderPermanentTokenConfiguration'
      - '../Classes/Configuration/GuzzleConfiguration'

  bynder2.cache.fileinfo:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['bynder2_file_response']

  bynder2.storages:
    class: SplObjectStorage
    factory: ['@JWeiland\Bynder2\Repository\BynderStorageFactory', 'getBynderStorages']

  bynder2.qb.sys_file:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'sys_file'

  JWeiland\Bynder2\Command\SyncBynderFilesCommand:
    arguments:
      $bynderStorages: '@bynder2.storages'
      $fileInfoCache: '@bynder2.cache.fileinfo'
    tags:
      - {name: 'console.command', command: 'fal:bynder:sync', schedulable: true}

  # Called by makeInstance in BynderDriver
  JWeiland\Bynder2\Configuration\ExtConf:
    public: true

  JWeiland\Bynder2\Controller\AuthorizationUrlController:
    arguments:
      - $bynderStorages: ['@bynder2.storages']

  # Called by makeInstance by TYPO3 ExtractorService
  JWeiland\Bynder2\Resource\BynderExtractor:
    public: true
    arguments:
      $cache: '@bynder2.cache.fileinfo'

  JWeiland\Bynder2\EventListener\GeneratePublicUrlForResourceEventListener:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent

  # Called by makeInstance in BynderDriver
  JWeiland\Bynder2\Repository\SysFileRepository:
    public: true
    arguments:
      $queryBuilder: '@bynder2.qb.sys_file'

  # Called by makeInstance from EXT:backend form elements
  JWeiland\Bynder2\Service\BynderClientFactory:
    public: true

  # Called by makeInstance from EXT:backend form elements
  JWeiland\Bynder2\Service\BynderService:
    public: true

  # Called by makeInstance in BynderDriver
  JWeiland\Bynder2\Utility\OrderingUtility:
    public: true
